### PR TITLE
stakepoold: Fix ticket handling to be more accurate.

### LINKED ISSUE #177: stakepoold has extra tickets due to use of stakepooluserinfo
stakepoold is using stakepooluserinfo to retrieve ticket data.  This isn't ideal because:

1) It contains immature tickets in addition to live.
2) A few tickets have the wrong status (probably caused by missed notifications).
3) It requires being called for each user after every block is voted.

### LINKED ISSUE #179: stakepoold needs an on-disk cache/backup for tickets/user voting config
This would allow stakepoold to continue to work in a disaster case where MySQL is down/deleted/hacked/whatever.

I was thinking along the lines of dcrd's peers.json where we just save a backup to disk every 10 minutes or so.

Kind of related to #134. We still want to work regardless of what data source is down -- whether it be MySQL or dcrstakepool's gRPC client sending us updates.

### PR DESCRIPTION
**Pull request by jolan**
This reworks the ticket handling of stakepoold.

Previously, it would do stakepooluserinfo for every user on startup and every block thereafter.

This switches it to use gettickets on startup and then add/remove tickets based on the OnNewTickets / OnSpentAndMissedTickets notifications.

stakepoold's ticket count now stays in sync with the live ticket count from getstakeinfo.

This also adds caching so voting can resume immediately.

Closes #177.
Closes #179.

### CODE REVIEW

File: backend/stakepoold/server.go [hunk 1]
```diff
@@ -323,20 +355,48 @@ func (ctx *appContext) loadData() {
...
+	res, nt.err = ctx.walletConnection.GetTransaction(nt.ticket)
+	nt.getDuration = time.Since(start)
+	if nt.err != nil {
+		return
+	}
+	for i := range res.Details {
+		_, ok := ctx.userVotingConfig[res.Details[i].Address]
+		if ok {
+			// multisigaddress will match if it belongs a pool user
+			nt.msa = res.Details[i].Address
```
Comment (chappjc) [inline backend/stakepoold/server.go]: Then break?

File: backend/stakepoold/rpcclient.go [hunk 2]
```diff
@@ -111,66 +109,68 @@ func connectWalletRPC(cfg *config) (*dcrrpcclient.Client, semver, error) {
...
-			hash, err := chainhash.NewHashFromStr(ticket.Ticket)
+			hash, err := chainhash.NewHashFromStr(gt.TxID)
 			if err != nil {
 				log.Infof("invalid ticket %v", err)
 				continue
 			}
-
-			userTickets[*hash] = users[p.msa].MultiSigAddress
-			ticketcount++
+			userTickets[*hash] = ctx.userVotingConfig[gt.Details[i].Address].MultiSigAddress
```
Comment (chappjc) [inline backend/stakepoold/rpcclient.go]: And break?
Also, I've seen a number of messed to ticket purchases where the outputs of the sstx have all the wrong indexes (e.g. swapped the Dc and Ds addresses).  I guess that's the idea here?  In case the op has done addticket for a non standard pool ticket?

File: backend/stakepoold/ntfnhandlers.go [hunk 3]
```diff
@@ -10,12 +10,33 @@ import (
...
+		OnNewTickets: func(blockHash *chainhash.Hash, blockHeight int64, stakeDifficulty int64, tickets []*chainhash.Hash) {
+			nt := NewTicketsForBlock{
+				blockHash:   blockHash,
+				blockHeight: blockHeight,
+				newTickets:  tickets,
+			}
+			ctx.newTicketsChan <- nt
+		},
+		OnSpentAndMissedTickets: func(blockHash *chainhash.Hash, blockHeight int64, stakeDifficulty int64, tickets map[chainhash.Hash]bool) {
+			ticketsFixed := make(map[*chainhash.Hash]bool)
```
Comment (chappjc) [inline backend/stakepoold/ntfnhandlers.go]: Hashing the pointer seems like trouble.  How come this is needed?

File: backend/stakepoold/server.go (hunk 1 above)
Comment (jolan) [inline backend/stakepoold/server.go]: Yep, good catch.

File: backend/stakepoold/rpcclient.go (hunk 2 above)
Comment (jolan) [inline backend/stakepoold/rpcclient.go]: Yeah that was the idea.  I wasn't sure about the user error stuff.

File: backend/stakepoold/ntfnhandlers.go (hunk 3 above)
Comment (jolan) [inline backend/stakepoold/ntfnhandlers.go]: I did that so ticketMetadata could be used for all the notification types.

File: backend/stakepoold/rpcclient.go (hunk 2 above)
Comment (chappjc) [inline backend/stakepoold/rpcclient.go]: I have to digest this a bit more, but I'm also thinking along the lines of not accidentally voting on malformed tickets (e.g. attempted cheaters) in addition to being sure to vote on the ones that were added manually.

Comment (jolan) [inline backend/stakepoold/rpcclient.go]: Oh right, I guess this means I need to add fee enforcement checks to stakepoold now.  Let me know if you have any other gotchas to consider.

File: backend/stakepoold/ntfnhandlers.go (hunk 3 above)
Comment (chappjc) [inline backend/stakepoold/ntfnhandlers.go]: By no means am I certain there's an issue, but two things feel funny. First is that memory leaks become much more likely with pointers, especially in the case of a map where you have buckets that need to be freed an so forth.  Second, how does a look up work?  Say you come in with another tx hash and want to see if it's in the table, can you get to it?  Hasn't the map hashed the pointer as a key, not the actual `chainhash.Hash`?

File: backend/stakepoold/server.go [hunk 4]
```diff
@@ -367,36 +427,158 @@ func (ctx *appContext) vote(wg *sync.WaitGroup, blockHash *chainhash.Hash, block
...
+
+	// We use pointer because it is the fastest accessor.
+	smtickets := make([]*ticketMetadata, 0, len(smt.smTickets))
+
+	var wg sync.WaitGroup // wait group for go routine exits
+
+	ctx.wgVoting.Wait() // wait for voting to finish
+
+	ctx.RLock()
+	for ticket, spent := range smt.smTickets {
```
Comment (chappjc) [inline backend/stakepoold/server.go]: The smTickets field still bugs me, being a `map[*chainhash.Hash]bool`.   It works as long as the only thing the map is used for is ranging over it to get the key-value pairs, but I'm afraid it might be used to lookup a hash, which won't work.

File: backend/stakepoold/server.go [hunk 5]
```diff
@@ -367,36 +427,158 @@ func (ctx *appContext) vote(wg *sync.WaitGroup, blockHash *chainhash.Hash, block
...
+		sm := &ticketMetadata{
+			spent:  spent,
+			ticket: ticket,
```
Comment (chappjc) [inline backend/stakepoold/server.go]: `ticketMetadata` could either have a non-pointer `chainhash.Hash` member or it could be referenced here.

File: backend/stakepoold/rpcclient.go [hunk 6]
```diff
@@ -111,66 +109,68 @@ func connectWalletRPC(cfg *config) (*dcrrpcclient.Client, semver, error) {
...
-	}
-	ctx.RUnlock()
+	var (
+		ticketcount, usercount int
+	)
 
 	userTickets := make(map[chainhash.Hash]string)
 
+	log.Infof("Running GetTickets, this may take awhile...")
+	tickets, err := ctx.walletConnection.GetTickets(false)
```
Comment (chappjc) [inline backend/stakepoold/rpcclient.go]: This takes a long time with 1000s of tickets.  I'm not sure this is practical unless `GetTickets` is accelerated.

File: backend/stakepoold/rpcclient.go [hunk 7]
```diff
@@ -111,66 +109,68 @@ func connectWalletRPC(cfg *config) (*dcrrpcclient.Client, semver, error) {
...
 		}
-		usercount++
 	}
 
+	ctx.RUnlock()
+
+	usersWithTickets := make(map[string]int)
+
+	for _, address := range userTickets {
+		usersWithTickets[address] = 1
```
Comment (chappjc) [inline backend/stakepoold/rpcclient.go]: Is this only for `usercount = len(usersWithTickets)` below or were there other plans?

File: backend/stakepoold/rpcclient.go (hunk 6 above)
Comment (jolan) [inline backend/stakepoold/rpcclient.go]: Yep I'm aware.  It should be able to be sped up a bit.

File: backend/stakepoold/rpcclient.go (hunk 7 above)
Comment (jolan) [inline backend/stakepoold/rpcclient.go]: Just for printing the user count.

**Comment by jolan** [comment]
Well I added fee checking and it works OK in my testing so far.  I'm going to see what I can do to improve the speed of GetTickets and then clean this up some more.

**Comment by chappjc** [comment]
@jolan Gonna test with your updates tonight if it's at a good spot.

**Comment by jolan** [comment]
Yes it's ready for testing/review. CC @marcopeereboom

File: backend/stakepoold/server.go [hunk 8]
```diff
@@ -301,46 +484,297 @@ func main() {
...
+
+	// getticket is used by processNewTickets and processSpentMissedTickets
+	// so we gracefully yield the processor until voting has completed
+	counter := 0
+	for {
+		lastVotedBlock := atomic.LoadInt64(&ctx.lastVotedBlock)
+		// XXX should really store and check the hash too but there's no
+		// atomic way to do that.  for now, fork blocks won't get vote
+		// prioritization.
+		if lastVotedBlock != nt.blockHeight {
```
Comment (chappjc) [inline backend/stakepoold/server.go]: Might be safer to do `if lastVotedBlock < nt.blockHeight`

File: backend/stakepoold/server.go [hunk 9]
```diff
@@ -371,43 +805,177 @@ func (ctx *appContext) vote(wg *sync.WaitGroup, blockHash *chainhash.Hash, block
...
+		ctx.liveTicketsMSA[ticket] = msa
+	}
+	ticketCountNew = len(ctx.liveTicketsMSA)
+	ctx.mtx.Unlock()
+	atomic.StoreUint64(&ctx.stats.TicketsLiveCount, uint64(ticketCountNew))
+
+	// Log ticket information outside of the handler.
+	go func() {
+		for ticket, msa := range addtickets {
+			atomic.AddUint64(&ctx.stats.TicketsNewCount, 1)
```
Comment (chappjc) [inline backend/stakepoold/server.go]: Outside the loop: `atomic.AddUint64(&ctx.stats.TicketsNewCount, len(addtickets))`

File: backend/stakepoold/rpcclient.go [hunk 10]
```diff
@@ -110,70 +112,170 @@ func connectWalletRPC(cfg *config) (*dcrrpcclient.Client, semver, error) {
...
+					if err != nil {
+						return false, fmt.Errorf("NewAmount failed: %v", err)
+					}
+					fees = feeAmount
+				}
+			}
+		}
+	}
+
+	in := dcrutil.Amount(0)
```
Comment (jolan) [inline backend/stakepoold/rpcclient.go]: Done

File: backend/stakepoold/rpcclient.go [hunk 11]
```diff
@@ -110,70 +112,170 @@ func connectWalletRPC(cfg *config) (*dcrrpcclient.Client, semver, error) {
...
+		amount, err := dcrutil.NewAmount(res.Vout[i].Value)
 		if err != nil {
-			log.Infof("Could not decode multisig address %v for %v: %v",
-				msa, v.Userid, err)
-			continue
+			return false, fmt.Errorf("NewAmount failed: %v", err)
 		}
+		out += amount
+	}
+	fees2 := in - out
```
Comment (jolan) [inline backend/stakepoold/rpcclient.go]: I updated the comment to reflect that this function is ported from wallet where it does have some tests (but more for the underlying functions/calculations).  Needs some more though.

File: backend/stakepoold/rpcclient.go [hunk 12]
```diff
@@ -110,70 +112,170 @@ func connectWalletRPC(cfg *config) (*dcrrpcclient.Client, semver, error) {
...
 
-			userTickets[*hash] = users[p.msa].MultiSigAddress
-			ticketcount++
+			// stake pool mode in dcrwallet works by checking the fee when the
+			// ticket is first seen.  If the fee is too low, the ticket is
+			// placed in the invalid bucket.  Otherwise, the ticket is added
+			// to the wallet.
+			// When stake pool-specific functionality in dcrwallet is removed,
+			// most likely all tickets, whether they pay the correct fee or not,
+			// will end up in live tickets list.
```
Comment (jolan) [inline backend/stakepoold/rpcclient.go]: This won't happen in dcrwallet for awhile.  I am just planning for when that day comes and trying to explain the logic.

File: backend/stakepoold/rpcclient.go [hunk 13]
```diff
@@ -110,70 +112,170 @@ func connectWalletRPC(cfg *config) (*dcrrpcclient.Client, semver, error) {
...
+				userTickets[*hash] = ctx.userVotingConfig[gt.Details[i].Address].MultiSigAddress
+			} else {
+				ticketFeesValid, err := nodeCheckTicketFee(ctx, gt.Hex, gt.BlockHash)
+				if ticketFeesValid {
+					userTickets[*hash] = ctx.userVotingConfig[gt.Details[i].Address].MultiSigAddress
+				} else {
+					atomic.AddUint64(&ctx.stats.TicketsIgnoredCount, 1)
+					log.Warnf("ignoring ticket %v for msa %v ticketFeesValid %v err %v",
+						*hash, ctx.userVotingConfig[gt.Details[i].Address].MultiSigAddress, ticketFeesValid, err)
+				}
```
Comment (jolan) [inline backend/stakepoold/rpcclient.go]: Right it was just called from main. I ended up putting it back to a read lock since I may want to call gettickets more than just at startup at some point.

File: backend/stakepoold/server.go [hunk 14]
```diff
@@ -242,18 +324,118 @@ func runMain() int {
...
+
+	ctx.printStats()
+
+	deferGetTickets := false
+
+	// get tickets now if we don't have any
+	if len(ctx.liveTicketsMSA) == 0 {
+		timenow := time.Now()
+		ctx.mtx.Lock()
+		ctx.liveTicketsMSA = walletGetTickets(ctx)
```
Comment (jolan) [inline backend/stakepoold/server.go]: Right, if we're stuck doing GetTickets() because we have 0 tickets and a block comes in, we will miss it.

This is why I added caching -- so stakepoold can start immediately voting the tickets it loads from disk.  Then when gettickets finishes processing, it will delete/append the differences.

File: backend/stakepoold/server.go [hunk 15]
```diff
@@ -301,46 +484,297 @@ func main() {
...
+			err = dec.Decode(&ctx.userVotingConfig)
+			if err != nil {
+				return err
+			}
+		}
+		log.Infof("Loaded %s from %s", dataKind, fullPath)
+		return nil
+	}
+
+	return nil
```
Comment (jolan) [inline backend/stakepoold/server.go]: I did make this an error and made lastseen not an error.

File: backend/stakepoold/server.go [hunk 16]
```diff
@@ -301,46 +484,297 @@ func main() {
...
+				log.Errorf("Failed to encode file %s: %v", ctx.dataPath, err)
+				continue
+			}
+		case "UserVotingConfig":
+			enc := gob.NewEncoder(w)
+			if err := enc.Encode(&ctx.userVotingConfig); err != nil {
+				log.Errorf("Failed to encode file %s: %v", ctx.dataPath, err)
+				continue
+			}
+		}
```
Comment (jolan) [inline backend/stakepoold/server.go]: Done

File: backend/stakepoold/server.go [hunk 17]
```diff
@@ -301,46 +484,297 @@ func main() {
...
-// winner contains all the bits and pieces required to vote and to print
-// statistics after usage.
-type winner struct {
+// ticketMetadata contains all the bits and pieces required to vote new tickets,
+// to look up new/missed/spent tickets, and to print statistics after usage.
+type ticketMetadata struct {
+	blockHeight  int64
 	msa          string                    // multisig
 	ticket       *chainhash.Hash           // ticket
+	spent        bool                      // spent (true) or missed (false)
```
Comment (jolan) [inline backend/stakepoold/server.go]: Yeah I just copied how it was named in the notification. I need to look at how/where that is set a bit more closely I guess.

File: backend/stakepoold/server.go (hunk 8 above)
Comment (jolan) [inline backend/stakepoold/server.go]: Done

File: backend/stakepoold/server.go (hunk 9 above)
Comment (jolan) [inline backend/stakepoold/server.go]: Done (and found a couple more spots)

**Comment by jolan** [comment]
I think functionality-wise this PR is good to go.

I updated my testnet stakepool setup and hit https://github.com/decred/dcrwallet/issues/825.

I'm also seeing an occasional hang when issuing gettickets().

It seems to happen 100% of the time with debuglevel=RPCC=debug.  When it hangs, I see the rpcclient output with the following output on the console:

```
2017-06-27 15:13:20.550 [INF] STPK: subscribed to notifications from dcrd
2017-06-27 15:13:20.550 [INF] STPK: Running GetTickets, this may take awhile...
2017-06-27 15:13:20.550 [INF] STPK: kicking off gettickets at 2017-06-27 15:13:20.550991638 -0500 CDT
2017-06-27 15:13:20.551 [TRC] RPCC: Sending command [gettickets] with id 3
2017-06-27 15:13:27.187 [TRC] RPCC: Received response for id 3 (result {"hashes":["1833c473a39c7d97fadb078151ccd4c9598dc009b87babe4bf19c30f40630c00",...
```

and in the log file:
```
2017-06-27 15:13:20.550 [INF] STPK: subscribed to notifications from dcrd
2017-06-27 15:13:20.550 [INF] STPK: Running GetTickets, this may take awhile...
2017-06-27 15:13:20.550 [INF] STPK: kicking off gettickets at 2017-06-27 15:13:20.550991638 -0500 CDT
2017-06-27 15:13:20.551 [TRC] RPCC: Sending command [gettickets] with id 3
```

So it looks like maybe the logger is hanging since the output doesn't match? Or maybe a locking issue?

File: backend/stakepoold/ntfnhandlers.go [hunk 18]
```diff
@@ -10,12 +10,31 @@ import (
 // Define notification handlers
 func getNodeNtfnHandlers(ctx *appContext, connCfg *dcrrpcclient.ConnConfig) *dcrrpcclient.NotificationHandlers {
 	return &dcrrpcclient.NotificationHandlers{
-		OnWinningTickets: func(blockHash *chainhash.Hash, blockHeight int64,
-			winningTickets []*chainhash.Hash) {
+		OnNewTickets: func(blockHash *chainhash.Hash, blockHeight int64, stakeDifficulty int64, tickets []*chainhash.Hash) {
```
Comment (marcopeereboom) [inline backend/stakepoold/ntfnhandlers.go]: I would not be offended by some sort of wrapping here.

File: backend/stakepoold/rpcclient.go [hunk 19]
```diff
@@ -1,13 +1,16 @@
 package main
 
 import (
+	"encoding/hex"
 	"fmt"
 	"io/ioutil"
+	"sync/atomic"
```
Comment (marcopeereboom) [inline backend/stakepoold/rpcclient.go]: Danger, danger!  This almost certainly is abused.  When synchronizing sections you pretty much always want to use a mutex.  atomic should only be used if you are creating your own locking types.

File: backend/stakepoold/rpcclient.go [hunk 20]
```diff
@@ -110,70 +113,193 @@ func connectWalletRPC(cfg *config) (*dcrrpcclient.Client, semver, error) {
...
+	if err != nil {
+		return false, fmt.Errorf("NewAmount failed: %v", err)
+	}
+
+	for i := range res.Vout {
+		switch res.Vout[i].ScriptPubKey.Type {
+		case "sstxcommitment":
+			for j := range res.Vout[i].ScriptPubKey.Addresses {
+				_, exists := ctx.feeAddrs[res.Vout[i].ScriptPubKey.Addresses[j]]
+				if exists {
```
Comment (marcopeereboom) [inline backend/stakepoold/rpcclient.go]: use continue idiom in order to unindent some.

File: backend/stakepoold/userdata/userdata.go [hunk 21]
```diff
@@ -16,7 +16,7 @@ type DBConfig struct {
 
 // UserData stores the current snapshot of the user voting config.
 type UserData struct {
-	sync.RWMutex
+	mtx              sync.RWMutex
```
Comment (marcopeereboom) [inline backend/stakepoold/userdata/userdata.go]: Don't use mtx; make it nameless so that the data structure itself can be locked.  That is the idomatic way.

File: backend/stakepoold/rpcclient.go [hunk 22]
```diff
@@ -110,70 +113,193 @@ func connectWalletRPC(cfg *config) (*dcrrpcclient.Client, semver, error) {
...
+
+	return true, nil
+}
+
+func walletGetTickets(ctx *appContext) map[chainhash.Hash]string {
 	// This is suboptimal to copy and needs fixing.
-	users := make(map[string]userdata.UserVotingConfig)
-	ctx.RLock()
+	userVotingConfig := make(map[string]userdata.UserVotingConfig)
+	ctx.mtx.RLock()
```
Comment (marcopeereboom) [inline backend/stakepoold/rpcclient.go]: use ctx.Rlock() please.  Mutexes should be nameless.

File: backend/stakepoold/rpcclient.go [hunk 23]
```diff
@@ -110,70 +113,193 @@ func connectWalletRPC(cfg *config) (*dcrrpcclient.Client, semver, error) {
...
+				}
+			}
+			break
 		}
-		usercount++
 	}
 
-	ticketNoun := pickNoun(ticketcount, "ticket", "tickets")
-	userNoun := pickNoun(usercount, "user", "users")
+	atomic.AddUint64(&ctx.stats.TicketsIgnoredCount, uint64(ticketsIgnoredCount))
```
Comment (marcopeereboom) [inline backend/stakepoold/rpcclient.go]: I am worried about this construct.  Are you sure this is correct?  I'd use a mutex to lock the data structure.  This is almost assuredly racing with something.  The value will be probably correct but the fact that you have 2 atomic operations in a row tells me that this is probably broken.

**Comment by jolan** [comment]
I can reproduce the hang with RPCC=trace on master so I will open a separate issue for that.

File: backend/stakepoold/server.go [hunk 24]
```diff
@@ -23,33 +28,75 @@ import (
...
 type appContext struct {
-	sync.RWMutex
+	// The following variable must only be used atomically.
+	// It is used to defer processing of the OnNewTickets and
+	// OnSpentAndMissedTickets notifications until the
+	// OnWinningTickets ntfn has been processed and voting
+	// has taken place.
+	lastVotedBlock int64
+
+	mtx sync.RWMutex
```
Comment (marcopeereboom) [inline backend/stakepoold/server.go]: Don't name mutexes.

File: backend/stakepoold/server.go [hunk 25]
```diff
@@ -242,18 +324,119 @@ func runMain() int {
 	log.Infof("Connected to dcrd (JSON-RPC API v%s) on %v",
 		nodeVer.String(), curnet.String())
 
-	_, height, err := nodeConn.GetBestBlock()
+	curHash, curBlock, err := nodeConn.GetBestBlock()
 	if err != nil {
 		log.Errorf("unable to get bestblock from dcrd: %v", err)
 		return 8
```
Comment (marcopeereboom) [inline backend/stakepoold/server.go]: It really is time to make this function return and error instead of an int.  Then on the caller you do

if err := runMain(); err != nil {
  fmt.Fprintf(os.Stderr, "%v\n", err)
}

The numbers are duplicated and mean nothing.  This also guaranteed has some errors that aren't printed making debugging painful.

File: backend/stakepoold/server.go [hunk 26]
```diff
@@ -242,18 +324,119 @@ func runMain() int {
...
+			log.Warnf("unable to load user voting preferences from disk "+
+				"cache: %v", err)
+		} else {
+			log.Infof("Loaded UserVotingConfig for %d users from disk cache",
+				len(userVotingConfig))
+		}
+	}
+
+	statsBlockHeight := atomic.LoadInt64(&ctx.stats.BlockHeight)
+	atomic.StoreInt64(&ctx.lastVotedBlock, statsBlockHeight)
```
Comment (marcopeereboom) [inline backend/stakepoold/server.go]: boo atomic!

File: backend/stakepoold/server.go [hunk 27]
```diff
@@ -242,18 +324,119 @@ func runMain() int {
...
+			}
+		}
+		// append new live tickets
+		for ticket, msa := range liveTicketsTemp {
+			_, exists := ctx.liveTicketsMSA[ticket]
+			if !exists {
+				ctx.liveTicketsMSA[ticket] = msa
+			}
+		}
+		atomic.StoreUint64(&ctx.stats.TicketsLiveCount, uint64(len(ctx.liveTicketsMSA)))
```
Comment (marcopeereboom) [inline backend/stakepoold/server.go]: atomic+mutex is probably wrong.

File: backend/stakepoold/server.go [hunk 28]
```diff
@@ -301,46 +485,304 @@ func main() {
...
+	for dataKind, dataVersion := range saveFiles {
+		var filesToPrune []string
+
+		if fileExists(ctx.dataPath) {
+			files, err := ioutil.ReadDir(ctx.dataPath)
+			if err != nil {
+				return err
+			}
+
+			for i, file := range files {
```
Comment (marcopeereboom) [inline backend/stakepoold/server.go]: Consider using continue.

File: backend/stakepoold/server.go [hunk 29]
```diff
@@ -301,46 +485,304 @@ func main() {
...
+				log.Debugf("entry %d => %s", i, file.Name())
+				if strings.HasPrefix(file.Name(), strings.ToLower(dataKind)) &&
+					strings.Contains(file.Name(), dataVersion) &&
+					strings.HasSuffix(file.Name(), ".gob") {
+					filesToPrune = append(filesToPrune, filepath.Join(ctx.dataPath, file.Name()))
+				}
+			}
+
+			if len(filesToPrune) > saveFilesToKeep {
```
Comment (marcopeereboom) [inline backend/stakepoold/server.go]: Consider using continue.

File: backend/stakepoold/server.go [hunk 30]
```diff
@@ -301,46 +485,304 @@ func main() {
...
 
-// loadData loads the saved data from the saved file.  If empty, missing, or
-// malformed file, just don't load anything and start fresh
-func (ctx *appContext) loadData() {
-	ctx.Lock()
-	defer ctx.Unlock()
+// saveData saves some appContext fields to a file so they can be loaded back
+// into memory at next run.
+func saveData(ctx *appContext) {
+	ctx.mtx.Lock()
```
Comment (marcopeereboom) [inline backend/stakepoold/server.go]: boo mtx!

File: backend/stakepoold/server.go [hunk 31]
```diff
@@ -301,46 +485,304 @@ func main() {
...
+}
+
+// getticket pulls the transaction information for a ticket from dcrwallet. This is a go routine!
+func (ctx *appContext) getticket(wg *sync.WaitGroup, nt *ticketMetadata) {
+	waitStart := time.Now()
+
+	// getticket is used by processNewTickets and processSpentMissedTickets
+	// so we gracefully yield the processor until voting has completed
+	counter := 0
+	for {
```
Comment (marcopeereboom) [inline backend/stakepoold/server.go]: This loop is very much not obvious and should be rewritten.

File: backend/stakepoold/server.go [hunk 32]
```diff
@@ -371,43 +813,177 @@ func (ctx *appContext) vote(wg *sync.WaitGroup, blockHash *chainhash.Hash, block
...
+	ticketCountNew := 0
+	ticketCountOld := 0
+
+	ctx.mtx.Lock()
+	ticketCountOld = len(ctx.liveTicketsMSA)
+	for ticket, msa := range addtickets {
+		ctx.liveTicketsMSA[ticket] = msa
+	}
+	ticketCountNew = len(ctx.liveTicketsMSA)
+	ctx.mtx.Unlock()
```
Comment (marcopeereboom) [inline backend/stakepoold/server.go]: Not loving atomic+mtx.

File: backend/stakepoold/server.go [hunk 33]
```diff
@@ -371,43 +813,177 @@ func (ctx *appContext) vote(wg *sync.WaitGroup, blockHash *chainhash.Hash, block
...
+	ctx.mtx.Lock()
+	ticketCountOld = len(ctx.liveTicketsMSA)
+	for _, ticket := range missedtickets {
+		delete(ctx.liveTicketsMSA, *ticket)
+	}
+	for _, ticket := range spenttickets {
+		delete(ctx.liveTicketsMSA, *ticket)
+	}
+	ticketCountNew = len(ctx.liveTicketsMSA)
+	ctx.mtx.Unlock()
```
Comment (marcopeereboom) [inline backend/stakepoold/server.go]: Not loving atomic+mtx.

File: backend/stakepoold/server.go [hunk 34]
```diff
@@ -461,53 +1037,88 @@ func (ctx *appContext) processWinningTickets(wt WinningTicketsForBlock) {
...
-	for {
-		select {
-		case <-ctx.reloadTickets:
-			start := time.Now()
-			newTickets, msg := walletFetchUserTickets(ctx)
-			end := time.Now()
+func (ctx *appContext) printStats() {
+	ctx.updateStats()
+
+	// TODO would be nice to differentiate expired from missed
```
Comment (marcopeereboom) [inline backend/stakepoold/server.go]: This should be mutexed and not be atomic.  Those 10 lines are racing.

File: backend/stakepoold/server.go (hunk 31 above)
Comment (chappjc) [inline backend/stakepoold/server.go]: To avoid the atomic stuff with `ctx.lastVotedBlock` and this loop, there could be a gate keeper function that returns a future (or just a channel) that signals when the vote goroutine has handled the latest block and it's cool for `processNewTickets` and `processSpentMissedTickets` to do their thing.

File: backend/stakepoold/rpcclient.go (hunk 23 above)
Comment (chappjc) [inline backend/stakepoold/rpcclient.go]: yeah, I think `Stats` could embed `sync.Mutex` and lock here and in [`printStats`](https://github.com/decred/dcrstakepool/pull/178/files/0a3952906c008fe90749ba4c58482258ffeb73de#diff-db56c53fc6985bfc454b56d97b3284b5R1082)

File: backend/stakepoold/server.go (hunk 31 above)
Comment (chappjc) [inline backend/stakepoold/server.go]: Ideally it would just read like `ctx.waitForVotes()` to keep this part clean.

File: backend/stakepoold/server.go [hunk 35]
```diff
@@ -371,43 +813,177 @@ func (ctx *appContext) vote(wg *sync.WaitGroup, blockHash *chainhash.Hash, block
...
+	ticketCountOld := 0
+
+	ctx.mtx.Lock()
+	ticketCountOld = len(ctx.liveTicketsMSA)
+	for ticket, msa := range addtickets {
+		ctx.liveTicketsMSA[ticket] = msa
+	}
+	ticketCountNew = len(ctx.liveTicketsMSA)
+	ctx.mtx.Unlock()
+	atomic.StoreUint64(&ctx.stats.TicketsLiveCount, uint64(ticketCountNew))
```
Comment (chappjc) [inline backend/stakepoold/server.go]: It's gonna be pretty difficult to keep the stats fields consistent with each other.  Either it doesn't matter, or they all need to be set at once.  In this function just adding a mutex to Stats and locking it might work, but since there are a few other spots where `ctx.stats.TicketsLiveCount` is potentially updated, I'm not sure what a solution to that might be.

File: backend/stakepoold/rpcclient.go (hunk 19 above)
Comment (jolan) [inline backend/stakepoold/rpcclient.go]: Done.

File: backend/stakepoold/rpcclient.go (hunk 20 above)
Comment (jolan) [inline backend/stakepoold/rpcclient.go]: Done.

File: backend/stakepoold/rpcclient.go (hunk 22 above)
Comment (jolan) [inline backend/stakepoold/rpcclient.go]: Done.

File: backend/stakepoold/rpcclient.go (hunk 23 above)
Comment (jolan) [inline backend/stakepoold/rpcclient.go]: I decided to remove all the stats stuff since it was pretty half-baked and I'm not sure it was very useful in the grand scheme of things.

File: backend/stakepoold/userdata/userdata.go (hunk 21 above)
Comment (jolan) [inline backend/stakepoold/userdata/userdata.go]: That one has to stay -- gob encoder that is used for the cache will choke otherwise.

File: backend/stakepoold/server.go (hunk 24 above)
Comment (jolan) [inline backend/stakepoold/server.go]: Done.

File: backend/stakepoold/server.go (hunk 25 above)
Comment (jolan) [inline backend/stakepoold/server.go]: Done.

File: backend/stakepoold/server.go (hunk 26 above)
Comment (jolan) [inline backend/stakepoold/server.go]: Done.

File: backend/stakepoold/server.go (hunk 27 above)
Comment (jolan) [inline backend/stakepoold/server.go]: Done.

File: backend/stakepoold/server.go (hunk 30 above)
Comment (jolan) [inline backend/stakepoold/server.go]: Done.

File: backend/stakepoold/server.go (hunk 31 above)
Comment (jolan) [inline backend/stakepoold/server.go]: I rewrote the loop but I'm still going to try to make it more like chappjc's suggestion.

File: backend/stakepoold/server.go (hunk 32 above)
Comment (jolan) [inline backend/stakepoold/server.go]: Done.

File: backend/stakepoold/server.go (hunk 33 above)
Comment (jolan) [inline backend/stakepoold/server.go]: Done.

File: backend/stakepoold/server.go (hunk 34 above)
Comment (jolan) [inline backend/stakepoold/server.go]: Yeah I just dropped everything about the stats.

**Comment by jolan** [comment]
atomic usage has been completely removed and I fixed all of the other nits that I could.  Still working well on testnet.

**Comment by jolan** [comment]
Hmm, using a channel works for awhile but eventually goes off the rails. I've reverted back for now.

**Comment by chappjc** [comment]
I was thinking that a `WaitGroup` might make implementing this easier.  Just a thought, haven't worked anything out in detail.

**Comment by jolan** [comment]
After switching to sending 1 time to 2 channels instead of sending 2 times to 1 channel, it appears to be working a lot better now.

**Comment by jolan** [comment]
Just to recap a bit:

The wrinkle with doing the ticket accounting this way is that we now have 3 notifications to process instead of 1.  The notifications come in essentially at the same time but in somewhat random order.

With the atomic locking, everything worked fine and it prioritized votes well.

To get rid of the atomic locking, I tried channels but my implementation had bugs and wasn't prioritizing votes very well.

So I went to waitgroups which work well but didn't prioritize votes very well since typically processNewTickets or processSpentMissedTickets would fire before processWinningTickets and we'd fire up GetTransaction calls immediately before voting could even start spinning up.

So I decided just to sleep processNewTickets/processSpentMissedTickets for 100ms to give processWinningTickets a head start.

Now things are running smoothly with no atomic usage present.  It's been running stably for ~40 hours and the ticketcount matches getstakeinfo output exactly. And votes are still going out within ~10ms on my test setup.

File: backend/stakepoold/userdata/userdata.go (hunk 21 above)
Comment (marcopeereboom) [inline backend/stakepoold/userdata/userdata.go]: Why can it not be nameless?

File: backend/stakepoold/server.go [hunk 36]
```diff
@@ -174,86 +219,156 @@ func runMain() int {
...
-	_, height, err := nodeConn.GetBestBlock()
+	// prune save data
+	err = pruneData(ctx)
 	if err != nil {
-		log.Errorf("unable to get bestblock from dcrd: %v", err)
-		return 8
+		log.Warnf("pruneData error: %v", err)
+	}
+
+	// not used currently
```
Comment (marcopeereboom) [inline backend/stakepoold/server.go]: please clean up comments below.

File: backend/stakepoold/server.go [hunk 37]
```diff
@@ -368,45 +728,178 @@ func (ctx *appContext) vote(wg *sync.WaitGroup, blockHash *chainhash.Hash, block
...
+		log.Infof("vote err %v", err)
+		w.err = err
+	} else {
+		w.txid = tx
+	}
 	w.sendDuration = time.Since(startSend)
 }
 
+func (ctx *appContext) processNewTickets(nt NewTicketsForBlock) {
+	time.Sleep(votingTargetTime) // give processWinningTickets time to vote
```
Comment (marcopeereboom) [inline backend/stakepoold/server.go]: Sleep is not the solution; please use a signaling mechanism.  Sleep is the new goto.

File: backend/stakepoold/userdata/userdata.go (hunk 21 above)
Comment (jrick) [inline backend/stakepoold/userdata/userdata.go]: https://play.golang.org/p/tnqaa1udVN

File: backend/stakepoold/server.go (hunk 36 above)
Comment (jolan) [inline backend/stakepoold/server.go]: I made the mutex nameless.  As I said previously, it had problems with the gob encoder but I forgot I rewrote it a bit so it's no longer a problem.

I also cleaned up the comments.

File: backend/stakepoold/server.go (hunk 37 above)
Comment (jolan) [inline backend/stakepoold/server.go]: I was able to find a solution that didn't involve sleeping.

**Comment by jolan** [comment]
Latest changes continued to run OK over the weekend.

**Comment by chappjc** [comment]
I've not tested the current code, but the latest changes to the waitgroup usage feel like a more elegant than the previous solution.

**Comment by chappjc** [comment]
Since this should be OK to test on a subset of stakepoold nodes, I'll give it a whirl on one mainnet wallet tonight and see how it does for 24 hrs or so.  I've seen many screwy sstx that the pool would vote on (mainly tickets manually added), but I'm a bit nervous about the validation code in these cases.  dcrwallet didn't care at voting time, only when deciding to add it to the stake pool manager, which of course is overridden by addticket.

**Comment by jolan** [comment]
Squashed and rebased to cleanup a bit.

File: backend/stakepoold/rpcclient.go [hunk 38]
```diff
@@ -110,70 +113,201 @@ func connectWalletRPC(cfg *config) (*dcrrpcclient.Client, semver, error) {
...
+		if err != nil {
+			return false, fmt.Errorf("NewAmount failed: %v", err)
+		}
+		out += amount
+	}
+	fees := in - out
+
+	if !feeAddrValid {
+		log.Warnf("Unknown pool commitment address %s for ticket %v",
+			feeAddr, res.Txid)
```
Comment (chappjc) [inline backend/stakepoold/rpcclient.go]: `feeAddr` will not be set, will still be "" that is.  Also,

File: backend/stakepoold/rpcclient.go [hunk 39]
```diff
@@ -110,70 +113,201 @@ func connectWalletRPC(cfg *config) (*dcrrpcclient.Client, semver, error) {
...
+				if !exists {
+					continue
+				}
+				feeAddr = res.Vout[i].ScriptPubKey.Addresses[j]
+				feeAddrValid = true
+				feeAmount, err := dcrutil.NewAmount(*res.Vout[i].ScriptPubKey.CommitAmt)
+				if err != nil {
+					return false, fmt.Errorf("NewAmount failed: %v", err)
+				}
+				commitAmt = feeAmount
```
Comment (chappjc) [inline backend/stakepoold/rpcclient.go]: I think this should break out of the for loop here, otherwise this will get the last fee address for a sstxcommitment output type (not that someone would really have 2 fee addresses at this point).  As your comment says it should be vout 1

File: backend/stakepoold/rpcclient.go [hunk 40]
```diff
@@ -110,70 +113,201 @@ func connectWalletRPC(cfg *config) (*dcrrpcclient.Client, semver, error) {
...
+		return false, fmt.Errorf("NewAmount failed: %v", err)
+	}
+
+	for i := range res.Vout {
+		switch res.Vout[i].ScriptPubKey.Type {
+		case "sstxcommitment":
+			for j := range res.Vout[i].ScriptPubKey.Addresses {
+				_, exists := ctx.feeAddrs[res.Vout[i].ScriptPubKey.Addresses[j]]
+				if !exists {
+					continue
```
Comment (chappjc) [inline backend/stakepoold/rpcclient.go]: If we want to know what the bad address was a vout 1, we need to store it here before continuing

File: backend/stakepoold/rpcclient.go [hunk 41]
```diff
@@ -110,70 +113,201 @@ func connectWalletRPC(cfg *config) (*dcrrpcclient.Client, semver, error) {
...
+			"are required to use this stake pool and is being skipped "+
+			"(required: %v, found %v)", feeAddr, res.Txid, feeNeeded, fees)
+
+		// Reject the entire transaction if it didn't
+		// pay the pool server fees.
+		return false, nil
+	}
+
+	log.Debugf("Accepted valid stake pool ticket %v committing %v in fees",
+		res.Txid, fees)
```
Comment (chappjc) [inline backend/stakepoold/rpcclient.go]: This is printing the transaction/mining fee.  Is the intent to print the commitAmt?

File: backend/stakepoold/rpcclient.go (hunk 40 above)
Comment (jolan) [inline backend/stakepoold/rpcclient.go]: Stored now.

File: backend/stakepoold/rpcclient.go (hunk 39 above)
Comment (jolan) [inline backend/stakepoold/rpcclient.go]: Good point, done.

File: backend/stakepoold/rpcclient.go (hunk 38 above)
Comment (jolan) [inline backend/stakepoold/rpcclient.go]: Set now so it will be printed.

File: backend/stakepoold/rpcclient.go (hunk 41 above)
Comment (jolan) [inline backend/stakepoold/rpcclient.go]: Yep, fixed, thanks.

**Comment by chappjc** [comment]
I have logs for about a week of running this with one wallet.  No errors, but I haven't compared with older versions of stakepoold logs to see if it's voting on every ticket.

**Comment by jolan** [comment]
I've seen my overall missed rate drop from 1.6% to 1.0% on testnet since I started development on this branch.  Unfortunately, it was difficult to keep better metrics due to the time elapsed, number of changes made, and doing development on other branches based off of this one.

Hard to tell how much of that is getting (more accurate?) ticket data via gettickets instead of stakepooluserinfo, the better vote prioritization in this branch, or the new stake algorithm causing more ticket purchases which causes the mining templates to refresh more, etc.

Anyway, this needs to go in since we want to continue to improve the stake code in dcrwallet like https://github.com/decred/dcrwallet/pull/886.  Removing stakepooluserinfo from stakepoold serves as a first step for this.
